apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-same-namespace-streamlit
  labels:
    template: quickstart-network-security-policy-streamlit
    app: {{ .Values.app.name }}-{{ .Values.app.zone }}
spec:
  podSelector: {}
  ingress:
    - from:
        - podSelector: {}
  policyTypes:
    - Ingress
