apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Values.app.name }}-{{ .Values.app.zone }}-{{ .Values.app.component }}
  labels:
    app: {{ .Values.app.name }}-{{ .Values.app.zone }}
stringData:
  # database-file-path: ${NAME}
  obj_store_bucket: {{ .Values.ostore_secrets.bucket }}
  obj_store_secret: {{ .Values.ostore_secrets.secret }}
  obj_store_user: {{ .Values.ostore_secrets.user }}
  obj_store_host: {{ .Values.ostore_secrets.host }}
